# Generated by Django 4.0.3 on 2023-04-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointment_date_time_appointment_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
